/** #ABSON WEDDING WEBSITE - GOOGLE APPS SCRIPT */
const SPREADSHEET_ID='1r8vV4oPPYwv8-4r7NELvvqukItVg4-va-lyjF86U0_U';
const RSVP_SHEET='RSVP';
const PHOTO_SHEET='Guest Photos';
const TEST_SHEET='Drive Test';
const PREFERRED_PHOTO_FOLDER_ID='1OcT9HW5yoRr3pcnmDHW0QGOQLJRkTq1j';
const FALLBACK_FOLDER_NAME='#ABSON Guest Uploads';
const MAX_FILE_SIZE_BYTES=25*1024*1024;

function setup(){const ss=SpreadsheetApp.openById(SPREADSHEET_ID);const r=getOrCreateSheet_(ss,RSVP_SHEET);ensureHeader_(r,['Timestamp','Name','Guests','Attendance','Event','Message']);const p=getOrCreateSheet_(ss,PHOTO_SHEET);ensureHeader_(p,['Timestamp','Guest Name','File Name','File Type','File Size (Bytes)','Drive Link','File ID']);const t=getOrCreateSheet_(ss,TEST_SHEET);ensureHeader_(t,['Timestamp','Test','Status','Details']);const folder=getPhotoFolder_();t.appendRow([new Date(),'Drive folder','READY',folder.getName()+' | '+folder.getUrl()]);return 'Setup completed. Drive folder: '+folder.getUrl()}

function doGet(e){try{const action=String((e&&e.parameter&&e.parameter.action)||'').trim();if(action==='guestPhotos')return getGuestPhotos_();return jsonResponse_({ok:true,project:'#ABSON Wedding Website',message:'Wedding endpoint is working',timestamp:new Date().toISOString()})}catch(err){return jsonResponse_({ok:false,error:String(err&&err.message||err)})}}

function getGuestPhotos_(){const photos=[];const seen={};try{const ss=SpreadsheetApp.openById(SPREADSHEET_ID);const sheet=ss.getSheetByName(PHOTO_SHEET);if(sheet&&sheet.getLastRow()>=2){const rows=sheet.getRange(2,1,sheet.getLastRow()-1,7).getValues();rows.reverse().forEach(function(r){const fileId=String(r[6]||'').trim();const url=String(r[5]||'').trim();if(!fileId&&!url)return;const key=fileId||url;if(seen[key])return;seen[key]=true;
let file=null;
if(fileId){try{file=DriveApp.getFileById(fileId)}catch(ignore){file=null}}
if(fileId&&!file){return}
if(!fileId&&!url){return}
let thumb=url;
if(file){try{file.setSharing(DriveApp.Access.ANYONE_WITH_LINK,DriveApp.Permission.VIEW)}catch(ignore){}thumb='https://drive.google.com/thumbnail?id='+encodeURIComponent(fileId)+'&sz=w1200'}
photos.push({timestamp:r[0]?new Date(r[0]).toISOString():'',name:String(r[1]||'Anonymous #ABSON'),fileName:String(r[2]||''),type:String(r[3]||''),size:Number(r[4]||0),url:thumb,fileId:fileId})})}}
catch(err){console.warn('Sheet photo feed failed: '+err)}
if(!photos.length){try{const folder=getPhotoFolder_();const files=folder.getFiles();while(files.hasNext()&&photos.length<60){const file=files.next();const id=file.getId();if(seen[id])continue;try{file.setSharing(DriveApp.Access.ANYONE_WITH_LINK,DriveApp.Permission.VIEW)}catch(ignore){}photos.push({timestamp:file.getDateCreated().toISOString(),name:'Anonymous #ABSON',fileName:file.getName(),type:file.getMimeType(),size:file.getSize(),url:'https://drive.google.com/thumbnail?id='+encodeURIComponent(id)+'&sz=w1200',fileId:id});seen[id]=true}}catch(err){console.warn('Drive photo feed failed: '+err)}}
return jsonResponse_({ok:true,photos:photos.slice(0,60)})}

function doPost(e){try{if(!e||!e.postData||!e.postData.contents)return jsonResponse_({ok:false,error:'POST body is empty or missing'});let payload;try{payload=JSON.parse(e.postData.contents)}catch(err){return jsonResponse_({ok:false,error:'Invalid JSON received'})}const action=String(payload.action||'').trim();if(action==='rsvp')return handleRSVP_(payload);if(action==='uploadGuestFile'||action==='upload'||action==='guestUpload')return handleGuestUpload_(payload);if(!action&&(payload.name!==undefined||payload.attendance!==undefined||payload.guests!==undefined))return handleRSVP_(payload);return jsonResponse_({ok:false,error:'Unknown action',action:action||'not specified'})}catch(err){console.error(err&&err.stack||err);return jsonResponse_({ok:false,error:String(err&&err.message||err)})}}

function handleRSVP_(p){const ss=SpreadsheetApp.openById(SPREADSHEET_ID),sheet=getOrCreateSheet_(ss,RSVP_SHEET);ensureHeader_(sheet,['Timestamp','Name','Guests','Attendance','Event','Message']);const name=cleanValue_(p.name);if(!name)throw new Error('Guest name is required.');const lock=LockService.getScriptLock();lock.waitLock(15000);try{sheet.appendRow([new Date(),name,cleanValue_(p.guests),cleanValue_(p.attendance),cleanValue_(p.event),cleanValue_(p.message)])}finally{lock.releaseLock()}return jsonResponse_({ok:true,type:'rsvp',message:'RSVP successfully recorded',name:name})}

function handleGuestUpload_(p){if(!p.base64)throw new Error('No file data received from website.');if(!p.fileName)throw new Error('No file name received.');let b=String(p.base64);if(b.indexOf(',')!==-1)b=b.split(',')[1];b=b.replace(/\s/g,'');if(!b)throw new Error('File data is empty.');if(Math.floor(b.length*.75)>MAX_FILE_SIZE_BYTES)throw new Error('File is too large. Please upload a file smaller than 25 MB.');const mime=String(p.mimeType||'application/octet-stream'),name=sanitizeFileName_(String(p.fileName)),guest=cleanValue_(p.guestName),bytes=Utilities.base64Decode(b);if(bytes.length>MAX_FILE_SIZE_BYTES)throw new Error('File is too large. Please upload a file smaller than 25 MB.');const folder=getPhotoFolder_();const lock=LockService.getScriptLock();lock.waitLock(30000);let file;try{file=folder.createFile(Utilities.newBlob(bytes,mime,name));try{file.setSharing(DriveApp.Access.ANYONE_WITH_LINK,DriveApp.Permission.VIEW)}catch(ignore){}}finally{lock.releaseLock()}const ss=SpreadsheetApp.openById(SPREADSHEET_ID),sheet=getOrCreateSheet_(ss,PHOTO_SHEET);ensureHeader_(sheet,['Timestamp','Guest Name','File Name','File Type','File Size (Bytes)','Drive Link','File ID']);sheet.appendRow([new Date(),guest,file.getName(),mime,file.getSize(),file.getUrl(),file.getId()]);return jsonResponse_({ok:true,type:'guest-upload',message:'File uploaded successfully',fileName:file.getName(),fileId:file.getId(),fileUrl:file.getUrl(),thumbnailUrl:'https://drive.google.com/thumbnail?id='+encodeURIComponent(file.getId())+'&sz=w1200',folderName:folder.getName(),folderUrl:folder.getUrl()})}

function getPhotoFolder_(){const props=PropertiesService.getScriptProperties(),saved=props.getProperty('ABSON_PHOTO_FOLDER_ID');if(saved){try{const f=DriveApp.getFolderById(saved);f.getName();return f}catch(err){props.deleteProperty('ABSON_PHOTO_FOLDER_ID')}}if(PREFERRED_PHOTO_FOLDER_ID){try{const f=DriveApp.getFolderById(PREFERRED_PHOTO_FOLDER_ID);f.getName();props.setProperty('ABSON_PHOTO_FOLDER_ID',f.getId());return f}catch(err){console.warn('Preferred folder unavailable: '+err)}}const f=DriveApp.createFolder(FALLBACK_FOLDER_NAME);props.setProperty('ABSON_PHOTO_FOLDER_ID',f.getId());return f}

function testDriveUpload(){const folder=getPhotoFolder_(),file=folder.createFile(Utilities.newBlob('This is a #ABSON Drive test file.','text/plain','ABSON-TEST-'+Date.now()+'.txt'));const ss=SpreadsheetApp.openById(SPREADSHEET_ID),sheet=getOrCreateSheet_(ss,TEST_SHEET);ensureHeader_(sheet,['Timestamp','Test','Status','Details']);sheet.appendRow([new Date(),'Drive upload','SUCCESS',file.getName()+' | '+file.getUrl()]);return{success:true,folderName:folder.getName(),folderUrl:folder.getUrl(),fileName:file.getName(),fileUrl:file.getUrl(),fileId:file.getId()}}

function checkConfiguration(){const result={spreadsheetId:SPREADSHEET_ID,spreadsheet:null,driveFolder:null,errors:[]};try{result.spreadsheet=SpreadsheetApp.openById(SPREADSHEET_ID).getName()}catch(err){result.errors.push('Spreadsheet access failed: '+err)}try{const f=getPhotoFolder_();result.driveFolder={id:f.getId(),name:f.getName(),url:f.getUrl()}}catch(err){result.errors.push('Drive access failed: '+err)}return result}

function getOrCreateSheet_(ss,name){return ss.getSheetByName(name)||ss.insertSheet(name)}
function ensureHeader_(sheet,headers){if(sheet.getLastRow()===0){sheet.getRange(1,1,1,headers.length).setValues([headers]);sheet.setFrozenRows(1);sheet.getRange(1,1,1,headers.length).setFontWeight('bold');sheet.autoResizeColumns(1,headers.length);return}const row=sheet.getRange(1,1,1,headers.length).getValues()[0];if(!row.some(v=>String(v||'').trim()!=='')){sheet.getRange(1,1,1,headers.length).setValues([headers]);sheet.setFrozenRows(1);sheet.getRange(1,1,1,headers.length).setFontWeight('bold')}}
function cleanValue_(v){if(v===null||v===undefined)return'';return typeof v==='object'?JSON.stringify(v):String(v).trim()}
function sanitizeFileName_(n){let x=n.replace(/[\\\/:*?"<>|#%{}]/g,'_').trim();if(!x)x='ABSON-Guest-Upload';return x.length>180?x.substring(0,180):x}
function jsonResponse_(data){return ContentService.createTextOutput(JSON.stringify(data)).setMimeType(ContentService.MimeType.JSON)}